version: '3.6'
services:
  es01:
    image: elasticsearch:7.16.2
    container_name: es01
    volumes:
      - elastic_data01:/usr/share/elasticsearch/data/
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health || exit 1" ]
      interval: 1000ms
      timeout: 5s
      retries: 5

  es02:
    image: elasticsearch:7.16.2
    container_name: es02
    volumes:
      - elastic_data02:/usr/share/elasticsearch/data/
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9201:9200'
      - '9301:9300'
    networks:
      - elk

  es03:
    image: elasticsearch:7.16.2
    container_name: es03
    volumes:
      - elastic_data03:/usr/share/elasticsearch/data/
    environment:
      - node.name=es03
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9202:9200'
      - '9302:9300'
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elk
    # elasticsearch.pingTimeout: 1000 
    # elasticsearch.requestTimeout: 3000

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elk

volumes:
  elastic_data01:
    driver: local
  elastic_data02:
    driver: local
  elastic_data03:
    driver: local

networks:
  elk:


